name:             Travel Model Two
description:      Travel Model Two Documentation
markdown:         redcarpet
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data

pygments:         false
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Travel Model Two
tagline:          'Metropolitan Transportation Commission'
url:              http://bayareametro.github.io/travel-model-two
shorturl:         bayareametro.github.io/travel-model-two

author:
  name:           'David Ory'
  url:            https://github.com/DavidOry

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MetropolitanTransportationCommission/travel-model-two/tree/gh-pages

# This is the list of pages to include in the header of the website.
pages_list:       
  Guide: 'guide/'
  Input: 'input/'
  Output: 'output/'
  Process: 'process/'
  Geographies: 'geographies/'
  Papers: 'papers/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
