name            : Travel Model Two
description     : Travel Model Two Documentation
markdown        : kramdown
kramdown:
  input         : GFM
  hard_wrap     : false

highlighter     : rouge

# Permalinks
permalink       : pretty

# Setup
title           : Travel Model Two
tagline         : 'Metropolitan Transportation Commission'
domain          : http://bayareametro.github.io
url             : http://bayareametro.github.io
baseurl         : /travel-model-two/

# Custom vars
version         : 1.0.0

github:
  repo          : https://github.com/BayAreaMetro/travel-model-two/tree/gh-pages

# This is the list of pages to include in the header of the website.
pages_list:       
  Guide           : 'guide/'
  Input           : 'input/'
  Output          : 'output/'
  Process         : 'process/'
  Geographies     : 'geographies/'
  Papers          : 'papers/'
  Network QA      : 'network_qa/'
  Network Building: 'netbuild/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
